### ISSUE TITLE
nitpick: bernoulli not bernouilli

### ISSUE THREAD

**Issue by nilsbecker** [igarnier/prbnmcn-dagger#1]
(just starting to get into it, this is just a thing that i noticed)

**Comment by igarnier** [comment]
Thanks a lot, I'll fix it shortly

**Comment by igarnier** [comment]
Fixed in commit https://gitlab.com/igarnier/monorepo/-/commit/285397c348fa54c6822e8d7f98a21b7fa5512c64

**Comment by igarnier** [comment]
Fixed in last release, closing. Thanks again for your report!
