### ISSUE TITLE
Smc does not appear to use or need log pdfs in distributions

### ISSUE THREAD

**Issue by nilsbecker** [igarnier/prbnmcn-dagger#12]
https://github.com/igarnier/prbnmcn-dagger/blob/93d5f0bb58d83ba62f3659d8470c43993f482f29/src/smc_inference.ml#L691

when new samples are generated, it appears that in Smc_inference, the log likelihood score of the samples is not used. this appears to make sense: in contrast to Lmh, no samples need to be mutated and re-scored. 

if that's true, it would be beneficial to change the interface. one would no longer require a `Dist.t` as input to `Smc_inference.sample` but instead only a `Gen.t` where `Gen` would be the one from `prbnmcn-stats`. ie only generation of samples without log likelihood info. 

this would be good because one can then chain generators e.g. for parameter mixture distributions, where actually calculating the likelihood of the combination is hard but generating samples is easy and in fact already nicely provided by `Gen.bind`.

**Comment by nilsbecker** [comment]
(the lack of `bind` in `Dist` is a hurdle that i just encountered in application code)

**Comment by igarnier** [comment]
We could generalize a bit the signature of `SMC`, indeed! Thanks for the suggestion.

**Comment by igarnier** [comment]
Implemented here https://gitlab.com/igarnier/monorepo/-/commit/1ac33938a31e5504d00ba2c06efc3814509e5db2

**Comment by igarnier** [comment]
0.0.5 was released with this feature, closing
