### ISSUE TITLE
acceptance rate in Lmh

### ISSUE THREAD

**Issue by nilsbecker** [igarnier/prbnmcn-dagger#16]
For judging the performance of any MCMC sampling scheme, it's informative to know the acceptance rate: the percentage of proposed MC moves that were accepted (probably best averaged over some adjustable window)

I believe the current API of `Lmh_inference` only provides `stream_samples` with no way to get this kind of sampling quality diagnostics.

I feel that would be an important feature.

Right now I'm trying to work around this by checking whether values returned in the sample stream actually change. But that's not entirely the same thing: internally, the update of, say an `int Lmh_inference.t` could have succeeded but the `int` sample produced may happen to be unchanged.

**Comment by igarnier** [comment]
I pushed a patch on `master` to record some basic statistics, would that be enough for your needs? https://gitlab.com/igarnier/monorepo/-/commit/13be4d2a10dfd64cb5c4f3dc3073e5b5fbd71b39

**Comment by igarnier** [comment]
Implemented in 0.0.5
