### ISSUE TITLE
Interface: swapping inference engines for a model

### ISSUE THREAD

**Issue by nilsbecker** [igarnier/prbnmcn-dagger#6]
i wonder if it would be possible to refactor the api so that models can be defined once and then run with different inference engines. currently, e.g. `Smc_inference` and `Lmh_inference` require a model that implements their respective sampling primitives.

different inference schemes require different additional parameters, such as a population size, resampling rule etc but it would be convenient if that could be outside of a model IMO.

**Comment by igarnier** [comment]
I agree that'd be great. This is already somewhat possible by functorizing the model over the signature of the desired sublanguage (I use this technique in some of the tests to avoid code duplication).

It's hard to make the interfaces of all inference algorithms totally uniform though: for instance, `Lmh_incremental_inference` exposes additional primitives which allow to specify more efficient models, these primitives make no sense for the other algorithms.
An other example: SMC exposes a `yield` primitive to trigger resampling, which doesn't exist in the other inference algorithms. We could decide to perform a `yield` on every `score` but that would reduce the amount of control of the user on when resamplings happen.

**Comment by nilsbecker** [comment]
yes, i see your point. the model not only describes the stochastic process but also has to call hooks into the sampling strategy (e.g. `yield`) which are strategy specific. 

in order to factor that out of the model definition, one would have to do some kind of inversion of control -- the strategy would need to drive the model with frequent possibilities for interruption to apply sampling-related actions. so basically every `sample` or `score` would have to `yield` but then the sampling strategy may choose to pass on many of these opportunities (based on some criterion) and simply continue running the model. 

the problem may be that the strategy does not have the information necessary to take the appropriate action.
