### ISSUE TITLE
cryptic errors from effect handling code

### ISSUE THREAD

**Issue by nilsbecker** [igarnier/prbnmcn-dagger#9]
I'm implementing some abc-smc like code using prbnmc-dagger. I have come across the situation that a program compiled fine but at runtime, raised an assertion error in https://github.com/igarnier/prbnmcn-dagger/blob/93d5f0bb58d83ba62f3659d8470c43993f482f29/src/smc_inference.ml#L712

I find this super weird as that line should never be reached -- the Effect type should be exhaustively matched already by the cases above (no?).

I think there is some subtle error in module resolution in my application -- but that may not even be the case as it does pass the type checker. Anyway, I have pushed a repository with two branches and granted you access. one branch is called "bug" and another "rescued". They differ in just 3 lines in "bin/gaussian_precision.ml". One branch triggers the bug and one doesn't.

To reproduce:
1. clone the mentioned repo and checkout the bug branch (and, for negative control, the rescued branch)
2. install required deps.
3. dune build
4. dune exec bin/gaussian_precision.exe

should be enough. Please don't hesitate to ask if this does not work.

I have seen the same assertion error once before; in that other example, interestingly, the error was triggered only when executing the inference in parallel (nthreads >1). 

I wonder if this may even be a bug in the Effect system?

**Comment by nilsbecker** [comment]
for more transparency i have made the repo containing the repro ( ;) ) public.

https://github.com/nilsbecker/prbnmc-test

**Comment by igarnier** [comment]
Thanks a lot for the report and the repro!

**Comment by igarnier** [comment]
I tried to reproduce the issue locally. I've OCaml version 5.1.1, and it didn't fail. Can you please share your OCaml version?
Edit: my bad, I was on the rescued branch.

**Comment by igarnier** [comment]
Ok, so here's what's happening.
Each time you instantiate the `Smc_inference.Make` module, you register fresh effects. The `.run` function provided by the resulting instance can only handle the effects defined locally in that instance. On the failing branch, the `Model` module uses a distinct instance from the `Thresholding` module. Hence, you cannot run terms constructed in `Model` with `T.run`.

I agree that the error is cryptic: I propose an error message suggesting that the user code produces effects not defined in this instance of `Smc_inference.Make`. Would that have helped?

**Comment by nilsbecker** [comment]
thanks for your insight, that makes sense! i think it's definitely something a user should be made aware of. i think an error message of the kind you propose would have helped me. one may also wonder whether the docs should contain some mention of this?

this issue reminds me of the difference between applicative and generative functors; the former are interoperable in the sense that if a functor produces two modules, each on the same input module, the resulting types are cross-compatible; while the latter are not. now `Smc_inference.Make` is applicative as it does not have an empty argument, but still the behavior of effect registration is more similar to a generative functor (do you agree?) while this is probably not a bug, one might avoid misunderstandings by making `Make` generative?

**Comment by igarnier** [comment]
Fixed upstream https://gitlab.com/igarnier/monorepo/-/commit/60396b9bb449a8cf559420b23d711b50e2468b5f
